HomeWork - Сетки страниц на флексах
htmlacademy-htmlcss/2324235-sedona-36 pull request #5
Opened 2023-03-02 21:24 UTC by brazilets

2023-03-06 17:06 UTC, andreysgra requested changes

2023-03-06 17:06 UTC, andreysgra commented on styles/styles.css
> +  justify-content: center;
А вот здесь использование `flex` ни к чему. Как мы видим в макете, элементы следуют один под другим, то есть в действии стандартная блочная модель. Свойствами `display: flex; flex-direction: column;` вы эмулируете это поведение, хотя оно уже заложено заранее (элементы `h3` и `p` имеют по умолчанию `dispay: block`). Отступы для текста лучше сделать за счёт `padding-top, padding-bottom` блока `.advanteges-container`.

2023-03-06 17:06 UTC, andreysgra commented on styles/styles.css
> +  padding-right: 347.5px;
Наверное нет необходимости в дробном значении.

2023-03-06 17:06 UTC, andreysgra commented on styles/styles.css
> +  width: 1200px;
Можно ширину `.services-list` не указывать, так как ширина уже определена общим контейнером `wrapper`.

2023-03-06 17:06 UTC, andreysgra commented on styles/styles.css
> +  align-items: center;
В `services-item` тоже эмуляция блочного поведения.

2023-03-06 17:06 UTC, andreysgra commented on styles/styles.css
> +  width: 1060px;
Ширину футеру, как и других блоков, которые тянутся на всю ширину контентной области указывать не нужно. Отступы лучше сделать за счёт паддингов по краям.

2023-03-06 17:06 UTC, andreysgra commented on styles/styles.css
> +  align-items: center;
Обычно внутри кнопки есть только текст и его выравнивать по центру с помощью флекс на мой взгляд избыточно. Для этого есть паддинги.

2023-03-06 17:06 UTC, andreysgra commented on styles/styles.css
> +  width: 1060px;
Про ширину - аналогично комментария к футеру.

2023-03-06 17:06 UTC, andreysgra commented on styles/styles.css
> +  width: 1060px;
Здесь тоже самое.

2023-03-06 17:06 UTC, andreysgra commented on catalog.html
> +            </ul>
А вот это что-то новое в разметке 😏 . Список тут должен быть один - список карточек гостиниц. Вы же на каждую карточку определили отдельный `ul`.

2023-03-06 20:49 UTC, brazilets commented on styles/styles.css
> +  align-items: center;
Вот этот вопрос не пойму. Судя по макету - там flex. Я тоже применил flex. Открыл в телефоне в трех разных браузерах, на компьютере в 4-х, отображение не меняется. Чем плохо применение flex в данном случае?

2023-03-07 17:13 UTC, andreysgra commented on styles/styles.css
> +  align-items: center;
Не нужно смотреть на эти свойства в макете. То, что вам нужно из макета - параметры шрифта, цвет, размеры. Всё остальное, от лукавого 😏 .

Оно не то чтобы плохо, оно не нужно в этом случае. Почему - я пояснил на примере `.advanteges-container` в самом первом комментарии. Вы применяете `flex` там, где без него вполне можно обойтись.

2023-03-07 17:15 UTC, merged